-- Pages villes : titre, description, extrait et texte reecrits (FR et EN), contenu local reel.
-- A lancer sur la base du serveur APRES le git pull qui met a jour includes/traduction.php (H1 et cartes).
-- Avant : sauvegarder les lignes concernees :
--   CREATE TABLE hw_details_page_bak_2026_10 AS SELECT * FROM hw_details_page WHERE id_page IN (32,33,37,38,39,40);
-- Retour en arriere :
--   UPDATE hw_details_page d JOIN hw_details_page_bak_2026_10 b ON b.id=d.id SET d.seo_titre=b.seo_titre, d.seo_description=b.seo_description, d.h1=b.h1, d.extrait=b.extrait, d.texte=b.texte;

-- marrakech (fr)
UPDATE hw_details_page SET seo_titre='Agence de communication à Marrakech : riads, luxe, loisirs', seo_description='Basés à Bab Doukala, nous suivons riads, agences immobilières de luxe et lieux de loisirs de Marrakech : site, réseaux sociaux, vidéo et référencement.', h1='Une agence de communication installée à Bab Doukala, au cœur de Marrakech', extrait='Notre bureau est à Bab Doukala. Riads, immobilier de luxe, loisirs, écoles : nous construisons la visibilité d''adresses marrakchies que nous croisons aussi dans la rue.', texte='<p>Notre bureau de Marrakech se trouve avenue My Abdellah, à Bab Doukala. Nous connaissons la ville parce que nous y travaillons tous les jours, et ce que nous voyons ne ressemble pas au reste du Maroc : une clientèle souvent étrangère, qui réserve en ligne, compare sur Google avant de venir et juge une adresse à ses photos. Pour un riad, une agence immobilière ou un lieu de loisirs, tout se joue sur trois choses : l''image, la langue et la place dans les résultats de recherche et sur les plateformes de réservation.</p>
<h3>Ce que nous avons fait pour des adresses de Marrakech</h3>
<ul>
<li><a href="/reference/noir-d-ivoire/13/">Noir d''Ivoire</a> et <a href="/reference/riad-turquoise/16/">Riad Turquoise</a> : deux riads de la médina. Identité visuelle, charte graphique, site, référencement et community management, avec en plus la vidéo pour Riad Turquoise.</li>
<li><a href="/reference/les-borjs-de-la-kasbah/7/">Les Borjs de la Kasbah</a> : photo et vidéo, site internet, référencement et campagnes sponsorisées.</li>
<li><a href="/reference/mur-et-prestige/1/">Mur &amp; Prestige</a>, <a href="/reference/barnes/30/">Barnes Marrakech</a>, <a href="/reference/le-meurice/38/">Le Meurice Immobilier</a> et <a href="/reference/swiss-luxury-real-estate/56/">Swiss Luxury Real Estate</a> : quatre agences d''immobilier de haut de gamme. Sites, mises à niveau, réseaux sociaux, vidéo et publicité en ligne selon les cas.</li>
<li><a href="/reference/urban-jump/49/">Urban Jump</a> et <a href="/reference/brothers-quad/57/">Brothers Quad</a> : des loisirs pour les familles et les voyageurs. Sites et versions mobiles ; pour Brothers Quad, aussi les fiches sur Airbnb, Booking, Viator ou Tripadvisor.</li>
<li><a href="/reference/le-jardin-secret/55/">Le Jardin Secret</a> : site, version mobile et boutique en ligne pour le jardin historique de la médina.</li>
<li><a href="/reference/la-commune-de-marrakech/32/">La Commune de Marrakech</a> : la conception et l''optimisation de son site depuis 2016.</li>
</ul>
<h3>Ce que nous pouvons faire pour vous</h3>
<p>Chaque projet commence par la même question : qui doit vous trouver, et dans quelle langue ? Ensuite seulement viennent les outils. Vous pouvez <a href="/service/creation-site-web-marrakech/">faire créer votre site web à Marrakech</a>, travailler <a href="/service/agence-de-referencement-naturel-a-marrakech/">votre référencement naturel</a>, confier votre <a href="/service/studio-de-design-graphique-marrakech/">identité visuelle à notre studio</a>, produire <a href="/service/production-photo-et-video-marrakech/">des photos et des vidéos</a> ou faire <a href="/service/gestion-des-reseaux-sociaux-a-marrakech/">animer vos réseaux sociaux</a>. Pour une marque qui démarre, la <a href="/service/strategie-de-marque-marrakech/">stratégie de marque</a> vient en premier.</p>
<p>Vous avez un projet à Marrakech ? Passez nous voir à Bab Doukala ou <a href="/contact/">écrivez-nous</a> : nous vous dirons honnêtement si nous sommes les bonnes personnes pour le mener.</p>' WHERE id_page=33 AND langue='fr';

-- marrakech (en)
UPDATE hw_details_page SET seo_titre='Communication agency in Marrakech: riads, luxury, leisure', seo_description='Based in Bab Doukala, we work with riads, luxury real estate agencies and leisure venues in Marrakech: website, social media, video and SEO.', h1='A communication agency based in Bab Doukala, in the heart of Marrakech', extrait='Our office is in Bab Doukala. Riads, luxury real estate, leisure, schools: we build the visibility of Marrakech businesses we also pass in the street.', texte='<p>Our Marrakech office is on Avenue My Abdellah, in Bab Doukala. We know the city because we work here every day, and it does not look like the rest of Morocco: guests are often foreign, they book online, compare on Google before they travel and judge a place by its photos. For a riad, a real estate agency or a leisure venue, everything rests on three things: the image, the language, and your place in search results and on booking platforms.</p>
<h3>What we have done for Marrakech businesses</h3>
<ul>
<li><a href="/en/reference/noir-d-ivoire/13/">Noir d''Ivoire</a> and <a href="/en/reference/riad-turquoise/16/">Riad Turquoise</a>: two riads in the medina. Visual identity, brand guidelines, website, SEO and community management, plus video for Riad Turquoise.</li>
<li><a href="/en/reference/les-borjs-de-la-kasbah/7/">Les Borjs de la Kasbah</a>: photo and video, website, SEO and sponsored campaigns.</li>
<li><a href="/en/reference/mur-et-prestige/1/">Mur &amp; Prestige</a>, <a href="/en/reference/barnes/30/">Barnes Marrakech</a>, <a href="/en/reference/le-meurice/38/">Le Meurice Immobilier</a> and <a href="/en/reference/swiss-luxury-real-estate/56/">Swiss Luxury Real Estate</a>: four high-end real estate agencies. Websites, upgrades, social media, video and online advertising depending on the case.</li>
<li><a href="/en/reference/urban-jump/49/">Urban Jump</a> and <a href="/en/reference/brothers-quad/57/">Brothers Quad</a>: leisure for families and travellers. Websites and mobile versions; for Brothers Quad, also the listings on Airbnb, Booking, Viator and Tripadvisor.</li>
<li><a href="/en/reference/le-jardin-secret/55/">Le Jardin Secret</a>: website, mobile version and online shop for the historic garden of the medina.</li>
<li><a href="/en/reference/la-commune-de-marrakech/32/">The City of Marrakech</a>: design and optimisation of its website since 2016.</li>
</ul>
<h3>What we can do for you</h3>
<p>Every project starts with the same question: who needs to find you, and in which language? Tools come after. You can <a href="/en/service/creation-site-web-marrakech/">have your website built in Marrakech</a>, work on <a href="/en/service/agence-de-referencement-naturel-a-marrakech/">your organic search</a>, hand your <a href="/en/service/studio-de-design-graphique-marrakech/">visual identity to our studio</a>, produce <a href="/en/service/production-photo-et-video-marrakech/">photos and videos</a> or have your <a href="/en/service/gestion-des-reseaux-sociaux-a-marrakech/">social media run for you</a>. For a brand that is just starting, <a href="/en/service/strategie-de-marque-marrakech/">brand strategy</a> comes first.</p>
<p>Have a project in Marrakech? Drop by Bab Doukala or <a href="/en/contact/">write to us</a>: we will tell you honestly whether we are the right people for it.</p>' WHERE id_page=33 AND langue='en';

-- casablanca (fr)
UPDATE hw_details_page SET seo_titre='Agence de communication Casablanca : hôtels, lounges, santé', seo_description='Appart''hôtels, restaurants lounge, cabinet médical, agence éducative : nos projets à Casablanca, du site web aux réseaux sociaux. Parlons du vôtre.', h1='Votre agence de communication à Casablanca, depuis Aïn Sebaâ', extrait='Une adresse à Aïn Sebaâ, des clients dans l''hôtellerie, la restauration, la santé et l''éducation : voici comment nous travaillons à Casablanca.', texte='<p>À Casablanca, tout le monde parle de business, et tout le monde est sollicité en permanence. Pour sortir du lot, il ne suffit pas d''être joli : il faut être trouvé au bon moment, par la bonne personne, et rassurer en quelques secondes. Nous avons une adresse dans le quartier d''Aïn Sebaâ et nous accompagnons des établissements qui vivent de leur réputation locale : hôtels, restaurants, cabinets et centres de formation.</p>
<h3>Quelques projets menés à Casablanca</h3>
<ul>
<li><a href="/reference/melliber-appart-hotel/4/">Melliber Appart Hôtel</a> : 90 studios et suites en bordure de l''océan. Nous avons dessiné le logotype et la charte graphique, puis conçu et développé le site.</li>
<li><a href="/reference/ocean-park-appart-hotel/48/">Ocean Park Appart''Hôtel</a> : des appart''hôtels haut de gamme avec piscine, spa et restaurant, pour lesquels nous avons réalisé le site web.</li>
<li><a href="/reference/maison-b/36/">Maison B</a> et <a href="/reference/antika-casa/37/">Antika Casa</a> : deux restaurants lounge. Site, réseaux sociaux, création vidéo et sponsoring, avec une ambiance à traduire à l''écran.</li>
<li><a href="/reference/dr-atannaz/53/">Dr Atannaz</a> : un cabinet de chirurgie plastique et esthétique. Un site et sa version mobile, avec la sobriété que demande un acte médical.</li>
<li><a href="/reference/caesa-mena/10/">Caesa Mena</a> : une agence éducative qui guide des étudiants internationaux. Identité visuelle, plan marketing, site, référencement, campagnes Google, community management et vidéo.</li>
</ul>
<h3>Ce que nous faisons pour vous</h3>
<p>Selon votre point de départ, nous commençons par <a href="/service/strategie-de-marque-casablanca/">votre identité de marque</a>, par <a href="/service/creation-site-web-casablanca/">un site web pensé pour convertir</a> ou par <a href="/service/agence-de-referencement-naturel-a-casablanca/">le référencement naturel</a> si votre site existe déjà. Nous produisons aussi <a href="/service/production-photo-et-video-casablanca/">les photos et les vidéos</a>, nous gérons <a href="/service/gestion-des-reseaux-sociaux-a-casablanca/">vos réseaux sociaux</a> et nous concevons <a href="/service/studio-de-design-graphique-casablanca/">vos supports graphiques</a>. Et si votre besoin est une application, nous <a href="/service/developpement-d-applications-mobiles-a-casablanca/">développons des applications mobiles</a> à Casablanca.</p>
<p>Un projet à Casablanca ? <a href="/contact/">Parlons-en</a>. Nous répondons par des questions plutôt que par un devis tout fait.</p>' WHERE id_page=32 AND langue='fr';

-- casablanca (en)
UPDATE hw_details_page SET seo_titre='Communication agency in Casablanca: hotels, lounges, health', seo_description='Apart-hotels, lounge restaurants, a medical practice, an education agency: our Casablanca projects, from websites to social media. Let''s talk.', h1='Your communication agency in Casablanca, from Aïn Sebaâ', extrait='An address in Aïn Sebaâ, clients in hospitality, restaurants, health and education: here is how we work in Casablanca.', texte='<p>In Casablanca everyone talks business, and everyone is solicited all the time. Standing out takes more than good looks: you have to be found at the right moment, by the right person, and reassure within seconds. We have an address in the Aïn Sebaâ district and we work with businesses that live on their local reputation: hotels, restaurants, practices and training centres.</p>
<h3>A few projects delivered in Casablanca</h3>
<ul>
<li><a href="/en/reference/melliber-appart-hotel/4/">Melliber Appart Hôtel</a>: 90 studios and suites by the ocean. We designed the logo and brand guidelines, then designed and built the website.</li>
<li><a href="/en/reference/ocean-park-appart-hotel/48/">Ocean Park Appart''Hôtel</a>: high-end apart-hotels with pool, spa and restaurant, for which we built the website.</li>
<li><a href="/en/reference/maison-b/36/">Maison B</a> and <a href="/en/reference/antika-casa/37/">Antika Casa</a>: two lounge restaurants. Website, social media, video and sponsoring, with an atmosphere to translate on screen.</li>
<li><a href="/en/reference/dr-atannaz/53/">Dr Atannaz</a>: a plastic and aesthetic surgery practice. A website and its mobile version, with the restraint a medical procedure calls for.</li>
<li><a href="/en/reference/caesa-mena/10/">Caesa Mena</a>: an education agency guiding international students. Visual identity, marketing plan, website, SEO, Google campaigns, community management and video.</li>
</ul>
<h3>What we do for you</h3>
<p>Depending on where you start, we begin with <a href="/en/service/strategie-de-marque-casablanca/">your brand identity</a>, with <a href="/en/service/creation-site-web-casablanca/">a website built to convert</a>, or with <a href="/en/service/agence-de-referencement-naturel-a-casablanca/">organic search</a> if your site already exists. We also produce <a href="/en/service/production-photo-et-video-casablanca/">photos and videos</a>, manage <a href="/en/service/gestion-des-reseaux-sociaux-a-casablanca/">your social media</a> and design <a href="/en/service/studio-de-design-graphique-casablanca/">your graphic materials</a>. And if you need an app, we <a href="/en/service/developpement-d-applications-mobiles-a-casablanca/">develop mobile applications</a> in Casablanca.</p>
<p>A project in Casablanca? <a href="/en/contact/">Let''s talk</a>. We answer with questions rather than a ready-made quote.</p>' WHERE id_page=32 AND langue='en';

-- rabat (fr)
UPDATE hw_details_page SET seo_titre='Agence marketing digital à Rabat, de l''école à la PME', seo_description='KGS et CPGE Ibn Ghazi nous ont confié leur présence en ligne à Rabat. Écoles, PME, startups : site, référencement et réseaux sociaux sur mesure.', h1='Le marketing digital à Rabat, pensé pour les écoles et les entreprises', extrait='Deux établissements scolaires de Rabat nous ont confié leur communication. Voilà ce que nous en avons retenu pour les écoles, les PME et les startups de la capitale.', texte='<p>Rabat n''est pas Casablanca. Ici, la vie économique tourne beaucoup autour de l''enseignement, des services et des institutions, et la confiance se construit lentement. Nous n''avons pas de bureau à Rabat : nos équipes sont à Marrakech et à Casablanca, et nous travaillons avec nos clients de la capitale en visioconférence et en déplacement. Ce que nous avons de solide à vous montrer, ce sont deux projets scolaires menés à Rabat.</p>
<h3>Ce que nous avons fait à Rabat</h3>
<ul>
<li><a href="/reference/kgs-rabat/20/">L''école Khalil Gibran (KGS)</a>, créée en 1986 : conseil en identité visuelle, charte graphique, plan marketing, site internet, référencement, community management, photographie, vidéo, décoration murale et affiches grand format. Un accompagnement complet, de l''image de l''école à ses murs.</li>
<li><a href="/reference/ibnghazi/26/">Les CPGE Ibn Ghazi</a>, classes préparatoires privées dont le premier centre est à Rabat : plan marketing, site internet, référencement, community management, photo et vidéo.</li>
</ul>
<p>Ces deux dossiers nous ont appris une chose utile pour tout établissement ou toute entreprise de la ville : les parents, les étudiants et les clients cherchent d''abord sur Google et sur Instagram, puis ils comparent. Un site à jour, des photos honnêtes et des réponses rapides font la différence.</p>
<h3>Ce que nous pouvons faire pour vous</h3>
<p>Nous pouvons <a href="/service/creation-site-web-rabat/">concevoir votre site web</a>, travailler <a href="/service/agence-de-referencement-naturel-a-rabat/">votre visibilité dans Google</a>, <a href="/service/gestion-des-reseaux-sociaux-a-rabat/">animer vos réseaux sociaux</a>, produire <a href="/service/agence-de-production-audiovisuelle-photo-et-video-a-rabat/">vos contenus photo et vidéo</a> ou dessiner <a href="/service/studio-de-design-graphique-rabat/">vos supports graphiques</a>. Pour une marque à construire, nous commençons par <a href="/service/strategie-de-marque-rabat/">sa stratégie</a>.</p>
<p>Vous dirigez une école, une PME ou une startup à Rabat ? <a href="/contact/">Racontez-nous votre projet</a>.</p>' WHERE id_page=37 AND langue='fr';

-- rabat (en)
UPDATE hw_details_page SET seo_titre='Digital marketing agency in Rabat, from schools to SMEs', seo_description='KGS and CPGE Ibn Ghazi trusted us with their online presence in Rabat. Schools, SMEs, startups: tailored website, SEO and social media.', h1='Digital marketing in Rabat, built for schools and businesses', extrait='Two schools in Rabat entrusted us with their communication. Here is what we learned for the schools, SMEs and startups of the capital.', texte='<p>Rabat is not Casablanca. Economic life here revolves a lot around education, services and institutions, and trust builds slowly. We do not have an office in Rabat: our teams are in Marrakech and Casablanca, and we work with our clients in the capital by video call and on site. What we can solidly show you are two school projects carried out in Rabat.</p>
<h3>What we have done in Rabat</h3>
<ul>
<li><a href="/en/reference/kgs-rabat/20/">Khalil Gibran School (KGS)</a>, founded in 1986: visual identity advice, brand guidelines, marketing plan, website, SEO, community management, photography, video, wall decoration and large-format posters. A full service, from the school''s image to its walls.</li>
<li><a href="/en/reference/ibnghazi/26/">CPGE Ibn Ghazi</a>, private preparatory classes whose first centre is in Rabat: marketing plan, website, SEO, community management, photo and video.</li>
</ul>
<p>These two projects taught us something useful for any school or business in the city: parents, students and customers search on Google and Instagram first, then compare. An up-to-date site, honest photos and quick answers make the difference.</p>
<h3>What we can do for you</h3>
<p>We can <a href="/en/service/creation-site-web-rabat/">build your website</a>, work on <a href="/en/service/agence-de-referencement-naturel-a-rabat/">your visibility on Google</a>, <a href="/en/service/gestion-des-reseaux-sociaux-a-rabat/">run your social media</a>, produce <a href="/en/service/agence-de-production-audiovisuelle-photo-et-video-a-rabat/">your photo and video content</a> or design <a href="/en/service/studio-de-design-graphique-rabat/">your graphic materials</a>. For a brand still to be built, we start with <a href="/en/service/strategie-de-marque-rabat/">its strategy</a>.</p>
<p>Do you run a school, an SME or a startup in Rabat? <a href="/en/contact/">Tell us about your project</a>.</p>' WHERE id_page=37 AND langue='en';

-- tanger (fr)
UPDATE hw_details_page SET seo_titre='Agence marketing digital à Tanger, tournée vers l''export', seo_description='Industrie, négoce, logistique : nous aidons les entreprises de Tanger à se faire trouver, au Maroc et à l''étranger. Site multilingue, SEO, prospection.', h1='Le marketing digital à Tanger, entre le port, l''industrie et l''international', extrait='Tanger travaille avec le monde entier. Votre visibilité doit parler la même langue que vos clients, du Maroc à l''étranger.', texte='<p>Soyons clairs : nous n''avons pas de bureau à Tanger. Nos équipes sont à Marrakech et à Casablanca, et nous travaillons avec les entreprises de Tanger en visioconférence et en déplacement. Ce que nous apportons, c''est une méthode et des références comparables à ce que vivent beaucoup d''entreprises tangéroises : vendre à des professionnels, parfois à l''étranger, avec une image qui doit rassurer avant le premier rendez-vous.</p>
<h3>Des projets proches de vos enjeux</h3>
<ul>
<li><a href="/reference/medicomp/43/">Medicomp</a>, distributeur de pièces automobiles pour garages et distributeurs : une application web pour traiter une clientèle de professionnels.</li>
<li><a href="/reference/daba-pneu/25/">Daba Pneu</a>, plateforme du groupe Manupro : la digitalisation des services du groupe.</li>
<li><a href="/reference/sabware/51/">Sabware</a>, conseil en Salesforce : un site pour présenter une expertise technique à des décideurs.</li>
</ul>
<h3>Ce qui change quand on vise l''international</h3>
<p>Un client étranger ne rappelle pas : il compare et il passe. Il lui faut un site en plusieurs langues, des pages qui répondent vraiment à sa question et un référencement qui le fait arriver au bon endroit. Nous construisons des sites en français, en anglais et en arabe, et nous travaillons la prospection en ligne pour les entreprises qui vendent à d''autres entreprises.</p>
<p>Selon votre besoin, nous pouvons <a href="/service/creation-de-site-web-a-tanger/">créer votre site web</a>, travailler <a href="/service/agence-de-referencement-naturel-a-tanger/">votre référencement naturel</a>, soigner <a href="/service/studio-de-design-graphique-tanger/">votre image de marque</a> ou <a href="/service/automatisation-et-agents-ia-a-tanger/">automatiser une partie de vos relances avec des agents IA</a>.</p>
<p>Dites-nous ce que vous vendez et à qui : <a href="/contact/">écrivez-nous</a>, nous vous répondrons point par point.</p>' WHERE id_page=38 AND langue='fr';

-- tanger (en)
UPDATE hw_details_page SET seo_titre='Digital marketing agency in Tangier, aimed at export', seo_description='Industry, trade, logistics: we help Tangier businesses get found, in Morocco and abroad. Multilingual website, SEO, outbound prospecting.', h1='Digital marketing in Tangier, between the port, industry and the international market', extrait='Tangier works with the whole world. Your visibility has to speak the same language as your customers, from Morocco to abroad.', texte='<p>Let''s be clear: we do not have an office in Tangier. Our teams are in Marrakech and Casablanca, and we work with Tangier businesses by video call and on site. What we bring is a method and references comparable to what many Tangier businesses live through: selling to professionals, sometimes abroad, with an image that must reassure before the first meeting.</p>
<h3>Projects close to your challenges</h3>
<ul>
<li><a href="/en/reference/medicomp/43/">Medicomp</a>, distributor of car parts for garages and distributors: a web application to serve a professional clientele.</li>
<li><a href="/en/reference/daba-pneu/25/">Daba Pneu</a>, platform of the Manupro group: the digitalisation of the group''s services.</li>
<li><a href="/en/reference/sabware/51/">Sabware</a>, Salesforce consulting: a website to present technical expertise to decision makers.</li>
</ul>
<h3>What changes when you aim at the international market</h3>
<p>A foreign customer does not call back: they compare and move on. They need a multilingual website, pages that really answer their question, and search visibility that brings them to the right place. We build websites in French, English and Arabic, and we work on online prospecting for companies that sell to other companies.</p>
<p>Depending on your need, we can <a href="/en/service/creation-de-site-web-a-tanger/">build your website</a>, work on <a href="/en/service/agence-de-referencement-naturel-a-tanger/">your organic search</a>, polish <a href="/en/service/studio-de-design-graphique-tanger/">your brand image</a> or <a href="/en/service/automatisation-et-agents-ia-a-tanger/">automate part of your follow-ups with AI agents</a>.</p>
<p>Tell us what you sell and to whom: <a href="/en/contact/">write to us</a>, we will answer point by point.</p>' WHERE id_page=38 AND langue='en';

-- fes (fr)
UPDATE hw_details_page SET seo_titre='Agence marketing digital à Fès : patrimoine et visibilité', seo_description='Maisons d''hôtes, artisanat, enseignement : nous aidons les activités de Fès à se faire trouver en ligne, du site web aux réseaux sociaux.', h1='Faire connaître votre activité à Fès, entre médina et ville nouvelle', extrait='À Fès, le patrimoine attire des visiteurs du monde entier. Encore faut-il qu''ils trouvent votre adresse avant celle du voisin.', texte='<p>Nous n''avons pas de bureau à Fès : nos équipes sont à Marrakech et à Casablanca, et nous travaillons avec les porteurs de projets fassis en visioconférence et en déplacement. Fès a ses forces propres : un patrimoine reconnu, un artisanat vivant, des universités, un commerce actif. Ce sont des activités où l''on vend une histoire autant qu''un produit, et c''est précisément ce que nous savons mettre en ligne.</p>
<h3>Des références proches de vos métiers</h3>
<ul>
<li><a href="/reference/resin-world/11/">Resin World</a>, galerie d''art et boutique en ligne d''œuvres artisanales : nous avons livré son site en respectant les exigences d''une clientèle internationale.</li>
<li><a href="/reference/al-fahd-gallery/18/">Al Fahd Gallery</a>, galerie d''art en ligne qui promeut et vend des œuvres : nous l''avons accompagnée.</li>
<li><a href="/reference/yani-concept/21/">Yani Concept</a> : une gamme de produits d''argan bio issus du terroir marocain, que nous avons accompagnée.</li>
<li><a href="/reference/noir-d-ivoire/13/">Noir d''Ivoire</a> et <a href="/reference/riad-turquoise/16/">Riad Turquoise</a>, deux riads de Marrakech : l''hôtellerie de charme en ville ancienne, de l''identité visuelle au référencement.</li>
</ul>
<h3>Par où commencer ?</h3>
<p>Pour une maison d''hôtes ou un artisan, le premier chantier est souvent <a href="/service/creation-site-web-fes/">un site clair, qui donne envie et qui rassure</a>, suivi de <a href="/service/studio-de-design-graphique-fes/">visuels cohérents</a> et d''<a href="/service/gestion-des-reseaux-sociaux-a-fes/">un compte Instagram vivant</a>. Pour un établissement d''enseignement, c''est plutôt la <a href="/service/strategie-de-marque-fes/">stratégie de marque</a> puis le référencement. Nous pouvons aussi <a href="/service/agence-de-production-audiovisuelle-photo-et-video-a-fes/">produire vos photos et vidéos</a>.</p>
<p>Parlez-nous de votre projet à Fès : <a href="/contact/">écrivez-nous</a>, nous vous dirons par quoi commencer et ce que nous ne ferions pas à votre place.</p>' WHERE id_page=40 AND langue='fr';

-- fes (en)
UPDATE hw_details_page SET seo_titre='Digital marketing agency in Fez: heritage and visibility', seo_description='Guesthouses, crafts, education: we help Fez businesses get found online, from the website to social media, with real hospitality and art references.', h1='Make your business known in Fez, between the medina and the new town', extrait='In Fez, heritage attracts visitors from all over the world. They still have to find your address before your neighbour''s.', texte='<p>We do not have an office in Fez: our teams are in Marrakech and Casablanca, and we work with Fez project owners by video call and on site. Fez has its own strengths: recognised heritage, living crafts, universities, active trade. These are businesses where you sell a story as much as a product, and that is exactly what we know how to put online.</p>
<h3>References close to your trades</h3>
<ul>
<li><a href="/en/reference/resin-world/11/">Resin World</a>, art gallery and online shop of handmade works: we delivered its website to meet the demands of an international clientele.</li>
<li><a href="/en/reference/al-fahd-gallery/18/">Al Fahd Gallery</a>, online art gallery that promotes and sells works: we supported it.</li>
<li><a href="/en/reference/yani-concept/21/">Yani Concept</a>: a range of organic argan products from Moroccan terroir, which we supported.</li>
<li><a href="/en/reference/noir-d-ivoire/13/">Noir d''Ivoire</a> and <a href="/en/reference/riad-turquoise/16/">Riad Turquoise</a>, two riads in Marrakech: boutique hospitality in an old town, from visual identity to SEO.</li>
</ul>
<h3>Where to start?</h3>
<p>For a guesthouse or a craftsperson, the first job is often <a href="/en/service/creation-site-web-fes/">a clear website that makes people want to come and reassures them</a>, followed by <a href="/en/service/studio-de-design-graphique-fes/">consistent visuals</a> and <a href="/en/service/gestion-des-reseaux-sociaux-a-fes/">a living Instagram account</a>. For a school, it is more <a href="/en/service/strategie-de-marque-fes/">brand strategy</a> and then SEO. We can also <a href="/en/service/agence-de-production-audiovisuelle-photo-et-video-a-fes/">produce your photos and videos</a>.</p>
<p>Tell us about your project in Fez: <a href="/en/contact/">write to us</a>, we will tell you where to start and what we would not do for you.</p>' WHERE id_page=40 AND langue='en';

-- agadir (fr)
UPDATE hw_details_page SET seo_titre='Agence marketing digital à Agadir : tourisme et commerce', seo_description='Hôtels, loisirs, commerces : nous aidons les acteurs d''Agadir à être trouvés et réservés en ligne. Site, référencement, réseaux sociaux, vidéo.', h1='Le marketing digital à Agadir, du front de mer aux commerces du Souss', extrait='À Agadir, beaucoup de clients se décident sur leur téléphone, en vacances. Votre fiche, votre site et vos photos doivent convaincre en quelques secondes.', texte='<p>Nous n''avons pas de bureau à Agadir. Nos équipes sont à Marrakech et à Casablanca, et nous travaillons avec les entreprises d''Agadir en visioconférence et en déplacement. Ce qui fait la particularité de la ville, c''est son rythme : une clientèle de passage, souvent en vacances, qui cherche une chambre, une activité ou un restaurant depuis son téléphone et choisit en quelques minutes. Beaucoup de commerces et d''entreprises du Souss vivent aussi de cette saisonnalité.</p>
<h3>Des références proches de votre quotidien</h3>
<ul>
<li><a href="/reference/melliber-appart-hotel/4/">Melliber Appart Hôtel</a> et <a href="/reference/ocean-park-appart-hotel/48/">Ocean Park Appart''Hôtel</a>, deux appart''hôtels de bord de mer à Casablanca : identité visuelle et site pour l''un, site web pour l''autre.</li>
<li><a href="/reference/les-borjs-de-la-kasbah/7/">Les Borjs de la Kasbah</a> et <a href="/reference/the-white-camel-acacia/34/">The White Camel Acacia</a>, un hôtel dans le désert d''Agafay : photo, vidéo, site, référencement et campagnes sponsorisées.</li>
<li><a href="/reference/brothers-quad/57/">Brothers Quad</a> : quad, buggy et dromadaire, avec la gestion des fiches sur Booking, Viator, Tripadvisor, Airbnb, Expedia et Klook. C''est le cas typique d''une activité qui se remplit grâce aux plateformes.</li>
</ul>
<h3>Ce qui compte pour un acteur touristique</h3>
<p>Une photo honnête, un site rapide sur mobile, une fiche Google à jour et des avis récents pèsent plus que n''importe quelle campagne. C''est par là que nous commençons : <a href="/service/creation-site-web-agadir/">un site clair et rapide</a>, <a href="/service/referencement-seo/">un référencement local</a>, <a href="/service/studio-de-design-graphique-agadir/">des visuels soignés</a> et, si vous le souhaitez, <a href="/service/automatisation-et-agents-ia-a-agadir/">un assistant IA qui répond aux demandes de réservation</a>.</p>
<p>Votre activité est à Agadir ? <a href="/contact/">Écrivez-nous</a> avec votre lien Google ou votre site : nous regarderons ensemble ce qui peut vous rapporter des réservations dès cette saison.</p>' WHERE id_page=39 AND langue='fr';

-- agadir (en)
UPDATE hw_details_page SET seo_titre='Digital marketing agency in Agadir: tourism and retail', seo_description='Hotels, leisure, shops: we help Agadir businesses get found and booked online. Fast mobile website, local SEO, social media, photo and video.', h1='Digital marketing in Agadir, from the seafront to the shops of the Souss', extrait='In Agadir, many customers decide on their phone, on holiday. Your listing, website and photos must convince within seconds.', texte='<p>We do not have an office in Agadir. Our teams are in Marrakech and Casablanca, and we work with Agadir businesses by video call and on site. What makes the city particular is its rhythm: passing guests, often on holiday, who look for a room, an activity or a restaurant on their phone and choose within minutes. Many shops and companies of the Souss region also live on this seasonality.</p>
<h3>References close to your daily life</h3>
<ul>
<li><a href="/en/reference/melliber-appart-hotel/4/">Melliber Appart Hôtel</a> and <a href="/en/reference/ocean-park-appart-hotel/48/">Ocean Park Appart''Hôtel</a>, two seaside apart-hotels in Casablanca: visual identity and website for one, website for the other.</li>
<li><a href="/en/reference/les-borjs-de-la-kasbah/7/">Les Borjs de la Kasbah</a> and <a href="/en/reference/the-white-camel-acacia/34/">The White Camel Acacia</a>, a hotel in the Agafay desert: photo, video, website, SEO and sponsored campaigns.</li>
<li><a href="/en/reference/brothers-quad/57/">Brothers Quad</a>: quad, buggy and camel rides, including listings on Booking, Viator, Tripadvisor, Airbnb, Expedia and Klook. A typical case of an activity that fills up through platforms.</li>
</ul>
<h3>What matters for a tourism business</h3>
<p>An honest photo, a fast mobile website, an up-to-date Google listing and recent reviews weigh more than any campaign. That is where we start: <a href="/en/service/creation-site-web-agadir/">a clear, fast website</a>, <a href="/en/service/referencement-seo/">local SEO</a>, <a href="/en/service/studio-de-design-graphique-agadir/">careful visuals</a> and, if you wish, <a href="/en/service/automatisation-et-agents-ia-a-agadir/">an AI assistant that answers booking requests</a>.</p>
<p>Is your business in Agadir? <a href="/en/contact/">Write to us</a> with your Google link or website: we will look together at what can bring you bookings this season.</p>' WHERE id_page=39 AND langue='en';
