-- Accueil + pages service x ville : seo_titre, seo_description (et h1 quand fourni), FR et EN.
-- Sauvegarde avant :
--   CREATE TABLE hw_details_service_bak_2026_10 AS SELECT * FROM hw_details_service;
--   CREATE TABLE hw_details_config_bak_2026_10 AS SELECT * FROM hw_details_config;
-- Retour en arriere :
--   UPDATE hw_details_service d JOIN hw_details_service_bak_2026_10 b ON b.id=d.id SET d.seo_titre=b.seo_titre, d.seo_description=b.seo_description, d.h1=b.h1;
--   UPDATE hw_details_config d JOIN hw_details_config_bak_2026_10 b ON b.langue=d.langue AND b.id_config=d.id_config SET d.titre=b.titre, d.description=b.description;

UPDATE hw_details_config SET titre='Agence marketing digital et création de site web au Maroc', description='Agence marketing digital leader au Maroc : création de site web, SEO et première page de Google, réseaux sociaux, applications et agents IA.' WHERE id_config=0 AND langue='fr';
UPDATE hw_details_config SET titre='Digital marketing agency and website creation in Morocco', description='Leading digital marketing agency in Morocco: website creation, SEO and Google first page, social media, apps and AI agents.' WHERE id_config=0 AND langue='en';

UPDATE hw_details_service SET seo_titre='Meilleure agence web à Casablanca : experts en sites', seo_description='Création de site web à Casablanca : site vitrine, boutique en ligne et plateforme sur mesure, conçus pour transformer vos visiteurs en clients.', h1='Un site web à Casablanca qui travaille pour vous, pas seulement une vitrine' WHERE slug='creation-site-web-casablanca' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Best web agency in Casablanca: website experts', seo_description='Website creation in Casablanca: showcase site, online shop and custom platform, designed to turn your visitors into customers.', h1='A website in Casablanca that works for you, not just a showcase' WHERE slug='creation-site-web-casablanca' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top agence de création de site web à Marrakech', seo_description='Agence de création de site web à Marrakech : site vitrine, e-commerce et plateforme sur mesure pour entrepreneurs et sociétés de tous les secteurs.', h1='Faire créer son site web à Marrakech, avec une équipe qui connaît la ville' WHERE slug='creation-site-web-marrakech' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top website creation agency in Marrakech', seo_description='Website creation agency in Marrakech: showcase site, e-commerce and custom platform for entrepreneurs and companies in every sector.', h1='Have your website built in Marrakech, by a team that knows the city' WHERE slug='creation-site-web-marrakech' AND langue='en';
UPDATE hw_details_service SET seo_titre='Création de site web à Rabat : top agence web', seo_description='Entrepreneurs, PME, cabinets, établissements : une agence web à Rabat pour créer un site clair, rapide, facile à mettre à jour et qui attire des clients.', h1='Création de site web à Rabat : un site qui attire des clients' WHERE slug='creation-site-web-rabat' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Website creation in Rabat: top web agency', seo_description='Entrepreneurs, SMEs, practices, institutions: a web agency in Rabat to build a clear, fast, easy-to-update website that attracts customers.', h1='Website creation in Rabat: a site that attracts customers' WHERE slug='creation-site-web-rabat' AND langue='en';
UPDATE hw_details_service SET seo_titre='Création de Site Web à Tanger : top agence web', seo_description='Création de Site Web à Tanger pour entrepreneurs et sociétés : site vitrine, e-commerce et visibilité sur Google. Travail à distance, échanges réguliers.', h1='Un site web à Tanger qui parle à vos clients' WHERE slug='creation-de-site-web-a-tanger' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Website Creation in Tangier: top web agency', seo_description='Website creation in Tangier for entrepreneurs and companies: showcase site, e-commerce and Google visibility. Remote work, regular exchanges.', h1='A website in Tangier that speaks to your customers' WHERE slug='creation-de-site-web-a-tanger' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top agence de création de sites web à Fès', seo_description='Agence de création de sites web à Fès : site vitrine, e-commerce et plateforme sur mesure pour entreprises, écoles, commerces et hébergements.', h1='Un site web à Fès qui raconte votre histoire' WHERE slug='creation-site-web-fes' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top website creation agency in Fez', seo_description='Website creation agency in Fez: showcase site, e-commerce and custom platform for businesses, schools, shops and guesthouses.', h1='A website in Fez that tells your story' WHERE slug='creation-site-web-fes' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top agence de création de sites web à Agadir', seo_description='Agence de création de sites web à Agadir pour hôtels, loisirs et commerces : un site rapide sur mobile, rassurant et bien placé sur Google.', h1='Votre site web à Agadir : rapide sur téléphone, prêt à recevoir des clients' WHERE slug='creation-site-web-agadir' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top website creation agency in Agadir', seo_description='Website creation agency in Agadir for hotels, leisure and shops: a site that loads fast on mobile, reassures in seconds and gets found on Google.', h1='Your website in Agadir: fast on phones, ready to receive customers' WHERE slug='creation-site-web-agadir' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top agence de design graphique à Casablanca', seo_description='Agence de design graphique à Casablanca : logotype, charte graphique, brochures, menus et affiches. Notre studio dessine l''image de votre marque.', h1='Le design graphique à Casablanca, du logo aux supports du quotidien' WHERE slug='studio-de-design-graphique-casablanca' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top graphic design agency in Casablanca', seo_description='Graphic design agency in Casablanca: logo, brand guidelines, brochures, menus and posters. Our studio designs the image of your brand.', h1='Graphic design in Casablanca, from the logo to everyday materials' WHERE slug='studio-de-design-graphique-casablanca' AND langue='en';
UPDATE hw_details_service SET seo_titre='Meilleur graphiste à Marrakech : identité visuelle', seo_description='Agence de design graphique à Marrakech : identité visuelle, logotype, cartes de visite, menus et affiches pour tous les secteurs.', h1='Donnez un visage à votre marque, depuis notre studio de Marrakech' WHERE slug='studio-de-design-graphique-marrakech' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Best graphic designer in Marrakech: visual identity', seo_description='Graphic design agency in Marrakech: visual identity, logo, business cards, menus and posters for businesses and venues in every sector.', h1='Give your brand a face, from our Marrakech studio' WHERE slug='studio-de-design-graphique-marrakech' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top studio de design graphique à Rabat', seo_description='Agence de design graphique à Rabat : charte graphique, supports imprimés, affiches grand format, décoration murale. Votre image, de A à Z.', h1='Le design graphique à Rabat, pour les entreprises et les établissements' WHERE slug='studio-de-design-graphique-rabat' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top graphic design studio in Rabat', seo_description='Graphic design agency in Rabat: brand guidelines, print materials, large-format posters, wall decoration. Your image, from A to Z.', h1='Graphic design in Rabat, for businesses and institutions' WHERE slug='studio-de-design-graphique-rabat' AND langue='en';
UPDATE hw_details_service SET seo_titre='Graphiste à Tanger : une identité visuelle qui se remarque', seo_description='Logo, charte, plaquettes et catalogues pour les entreprises de Tanger. Nous travaillons à distance et nous vous présentons chaque étape en visio.', h1='Une identité visuelle à Tanger qui inspire confiance dès le premier regard' WHERE slug='studio-de-design-graphique-tanger' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Graphic designer in Tangier: a standout visual identity', seo_description='Logo, brand guidelines, brochures and catalogues for Tangier businesses. We work remotely and present each step to you by video call.', h1='A visual identity in Tangier that inspires trust at first glance' WHERE slug='studio-de-design-graphique-tanger' AND langue='en';
UPDATE hw_details_service SET seo_titre='Design graphique à Fès : identité de commerces et d''hôtes', seo_description='Logo, étiquettes, menus, brochures : des identités cohérentes pour les commerces, artisans et hébergements de Fès, à distance ou sur rendez-vous.', h1='Une image de marque à Fès qui respecte votre savoir-faire' WHERE slug='studio-de-design-graphique-fes' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Graphic design in Fez: identity for shops and hosts', seo_description='Logo, labels, menus, brochures: consistent identities for shops, craftspeople and guesthouses in Fez, remotely or by appointment.', h1='A brand image in Fez that respects your know-how' WHERE slug='studio-de-design-graphique-fes' AND langue='en';
UPDATE hw_details_service SET seo_titre='Design graphique à Agadir : logo, charte et supports', seo_description='Hôtels, restaurants, boutiques et activités de loisirs : logo, charte graphique, menus et supports de communication, conçus par notre studio.', h1='Une identité visuelle à Agadir qui donne envie de pousser la porte' WHERE slug='studio-de-design-graphique-agadir' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Graphic design in Agadir: logo, guidelines and materials', seo_description='Hotels, restaurants, shops and leisure activities: logo, brand guidelines, menus and communication materials designed by our studio.', h1='A visual identity in Agadir that makes people want to walk in' WHERE slug='studio-de-design-graphique-agadir' AND langue='en';
UPDATE hw_details_service SET seo_titre='Meilleurs experts SEO à Marrakech : première page Google', seo_description='Agence Référencement Naturel Marrakech : audit, mots-clés, contenus et suivi pour viser la première page de Google. Expertise SEO expliquée simplement.', h1='Le référencement naturel à Marrakech, pour que vos clients vous trouvent avant de réserver ailleurs' WHERE slug='agence-de-referencement-naturel-a-marrakech' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Best SEO experts in Marrakech: Google first page', seo_description='Organic search agency in Marrakech: audit, keywords, content and follow-up to aim for Google''s first page. SEO expertise explained simply.', h1='Organic search in Marrakech, so customers find you before booking elsewhere' WHERE slug='agence-de-referencement-naturel-a-marrakech' AND langue='en';
UPDATE hw_details_service SET seo_titre='Meilleurs experts SEO à Casablanca : première page Google', seo_description='Nous avons positionné de grandes sociétés sur la première page de Google : nous maîtrisons son classement. Audit de votre site sur demande.', h1='Le SEO à Casablanca : viser la première page de Google, avec méthode' WHERE slug='agence-de-referencement-naturel-a-casablanca' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Best SEO experts in Casablanca: Google first page', seo_description='We have ranked large companies on Google''s first page: we master its ranking. Audit of your site on request.', h1='SEO in Casablanca: aiming for Google''s first page, with method' WHERE slug='agence-de-referencement-naturel-a-casablanca' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top référencement naturel à Rabat : première page Google', seo_description='Agence de référencement naturel à Rabat : audit, mots-clés, contenus et suivi pour entreprises et startups. Objectif : la première page de Google.', h1='Améliorer votre visibilité sur Google depuis Rabat' WHERE slug='agence-de-referencement-naturel-a-rabat' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top organic search in Rabat: Google first page', seo_description='Organic search agency in Rabat: audit, keywords, content and follow-up for businesses and startups. Goal: Google''s first page.', h1='Improve your visibility on Google from Rabat' WHERE slug='agence-de-referencement-naturel-a-rabat' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top consultant SEO à Tanger : première page Google', seo_description='Pages claires, mots-clés professionnels, contenus utiles : nous travaillons le classement en première page de Google. Audit sur demande.', h1='Un référencement pensé pour vos clients de Tanger et d''ailleurs' WHERE slug='agence-de-referencement-naturel-a-tanger' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top SEO consultant in Tangier: Google first page', seo_description='Clear pages, professional keywords, useful content: we work on first-page Google ranking. Audit on request.', h1='SEO built for your customers in Tangier and beyond' WHERE slug='agence-de-referencement-naturel-a-tanger' AND langue='en';
UPDATE hw_details_service SET seo_titre='Meilleur vidéographe à Casablanca : vidéo et photo', seo_description='Vidéographe à Casablanca : portrait, culinaire, mode, entreprise, événementiel. Vidéos de marque et reportages photo pour de nombreuses entreprises.', h1='De belles images à Casablanca, du portrait au culinaire, de la mode à l''entreprise' WHERE slug='production-photo-et-video-casablanca' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Best videographer in Casablanca: video and photo', seo_description='Videographer in Casablanca: portrait, food, fashion, corporate, events. Brand videos and photo reports for many businesses.', h1='Great images in Casablanca, from portrait to food, from fashion to corporate' WHERE slug='production-photo-et-video-casablanca' AND langue='en';
UPDATE hw_details_service SET seo_titre='Top production photo et vidéo à Marrakech : mariages', seo_description='Production photo et vidéo à Marrakech : mariages, événements, vidéos de marque, immobilier et reportages d''entreprise. Une équipe qui produit en interne.', h1='Photos et films à Marrakech, pour tous vos moments et toutes vos marques' WHERE slug='production-photo-et-video-marrakech' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Top photo and video production in Marrakech: weddings', seo_description='Photo and video production in Marrakech: weddings, events, brand videos, real estate and corporate reports. A team that produces in-house.', h1='Photos and films in Marrakech, for all your moments and brands' WHERE slug='production-photo-et-video-marrakech' AND langue='en';
UPDATE hw_details_service SET seo_titre='Production audiovisuelle à Rabat : photo, vidéo, événements', seo_description='Agence audiovisuelle à Rabat : films institutionnels, portraits, photos de produits et reportages d''événements pour entreprises et établissements.', h1='L''image de votre structure à Rabat, en photo et en vidéo' WHERE slug='agence-de-production-audiovisuelle-photo-et-video-a-rabat' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Audiovisual production in Rabat: photo, video, events', seo_description='Audiovisual agency in Rabat: corporate films, portraits, product photos and event reports for businesses and institutions.', h1='The image of your organisation in Rabat, in photo and video' WHERE slug='agence-de-production-audiovisuelle-photo-et-video-a-rabat' AND langue='en';
UPDATE hw_details_service SET seo_titre='Agence audiovisuelle à Fès : photo et vidéo d''hébergement', seo_description='Maisons d''hôtes, artisans, établissements : photos soignées et vidéos courtes pour le site et les réseaux, avec déplacement de l''équipe à Fès.', h1='Photographier et filmer Fès comme vous la vivez' WHERE slug='agence-de-production-audiovisuelle-photo-et-video-a-fes' AND langue='fr';
UPDATE hw_details_service SET seo_titre='Audiovisual agency in Fez: accommodation photo and video', seo_description='Guesthouses, craftspeople, businesses: careful photos and short videos for the website and social media, with our team travelling to Fez.', h1='Photograph and film Fez the way you live it' WHERE slug='agence-de-production-audiovisuelle-photo-et-video-a-fes' AND langue='en';
